version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.7
  pre_build:
    commands:
      - |
        if [ "$BUILD_TYPE" = "UNITTEST" ]; then
          # run unittest commands
          echo Test the python application.
          pip install -r requirements.txt
          flake8 app.py
          pytest
        fi
  build:
    commands:
      - |
        if [ "$BUILD_TYPE" = "BUILD" ]; then
          # run build commands
          echo Build the CSS using less.
          npm install -g less
          mkdir -p static/css
          lessc styles.less static/css/styles.css
        fi
artifacts:
  files:
    - '**/*'
  name: python-app-$(date +%y%m%d%H%M).zip
